### ISSUE TITLE
clipboard_set_text not working

### ISSUE THREAD

**Issue by kenlauescuadro** [GameMakerDiscord/GMEdit#36]
Simply the title.

I've tested:

if keyboard_check_pressed(ord("Q"))
{
    trace(string(finalproduct))
    clipboard_set_text(finalproduct)
}

The trace function works, while clipboard_set_text doesn't.

**Comment by YellowAfterlife** [comment]
What do you mean by "not working" specifically?

**Comment by kenlauescuadro** [comment]
It doesn't work in the sense that the current text in the clipboard will not be replaced by whatever string is in clipboard_set_text.

For example:
- The current text in the clipboard is "Hello"
- A clipboard_set_text function is run like this:
clipboard_set_text("Hi")
- Instead of the text in the clipboard being "Hi", it's still "Hello".

**Comment by Sidorakh** [comment]
This is actually a GameMaker issue and not a GMEdit issue. GMEdit does not modify how inbuilt functions (such as `clipboard_set_text`) work. If this function isn't working for you, file a bug with YoYoGames [here](https://accounts.yoyogames.com/contact-us). 

Bear in mind, some functions do not work on all platforms, such as `clipboard_set_text`, which does not work in HTML5 (and because of this, it doesn't work in GMLive.js either, which works off of the HTML5 export). Again, this is an issue with GameMaker Studio, and not GMEdit.

**Comment by kenlauescuadro** [comment]
I'm sorry to reopen this, but is there a way that one can copy text using the program's trace/show_message function, or with anyway? I can't seem to copy text that has been shown with the trace function, let alone copy the entire text said there.

**Comment by YellowAfterlife** [comment]
You can't copy trace text by default because GMS absorbs all keyboard events and also all mouse events.
Doing ```
browser_input_capture(false);
trace("hello!");
```
will work

**Comment by kenlauescuadro** [comment]
Thank you very much!
