### ISSUE TITLE
Cannot create or delete new file

### ISSUE THREAD

**Issue by Shadowblitz16** [GameMakerDiscord/GMEdit#42]
I cannot create, delete, move or copy, cut, paste new files.
does this require that the files already exist in the gml project from gamemaker studio 2?

**Comment by YellowAfterlife** [comment]
At this time you can only create new scripts, via right-click menu on scripts/script folders.

Selecting/copying/pasting resource tree items is not supported because the resource tree is an entirely custom thing; none of people promising to contribute something to it finished anything as of yet.

Each resource type has to be researched separately for what consequences removing it would bring (e.g. - does removing an object that's in a room corrupt the room? If so, add X hours to also implement a room format reader/writer first. What about it's child objects? )

**Comment by YellowAfterlife** [comment]
As of the March release you can create objects but it will not perform any checks upon destroying them.

Thank you for your glorious assistance with issues of personal concern or whatever
