### ISSUE TITLE
incorrect order of autocomplete items

### ISSUE THREAD

**Issue by love2d-lua** [GameMakerDiscord/GMEdit#54]
(smart match completion) If "sdm"  typed results in show_debug_message then for instance_create_layer (this is used often) I would type "icl", autocomplete results are not helpful,
 see snapshot.
<img width="274" alt="gmeditbug" src="https://user-images.githubusercontent.com/33927971/56375911-4eafce80-6224-11e9-822a-ea1062217d5a.PNG">

**Comment by YellowAfterlife** [comment]
This option is handled by [code editor itself](https://github.com/GameMakerDiscord/GMEdit/blob/a399ee9c8ac3c8db4920c7cf32b9e9e3f4ffb0bb/bin/resources/app/ace/src-noconflict/ext-language_tools.js#L1737-L1763) (someone [asked](https://github.com/GameMakerDiscord/GMEdit/issues/24) to expose that option, so I did).

Considering that GMEdit cannot really know which of these things you want, what do you expect to happen?

**Comment by love2d-lua** [comment]
Thanks for the link to code, smart match option is good, if 'sdm' and 'kcp' show show_debug_message and keyboard_check_pressed respectively on top of autocomplete list, then for 'icl' I should get instance_create_layer, that is the expectation.
From the code it looks like ACE editor's sorting  of autocomplete items is designed for Camelcase and gml function names are all snake case so the inconsistent behaviour.

**Comment by YellowAfterlife** [comment]
If you can build from git version or replace ext-language_tools.js by [the new version](https://github.com/GameMakerDiscord/GMEdit/blob/35fda625950d4103286dcfed21d883ab318d50dc/bin/resources/app/ace/src-noconflict/ext-language_tools.js), this enables forced result sorting for "smart match" completion.

I guess this is a bit better - you aren't going to get instance_create_layer from "icl" (io_clear gets in the way because the "distance" between matches is smaller), but you will get it from "icrl", "icly", or "icay".

**Comment by love2d-lua** [comment]
thank you very much!
